// Coffe Class fixed for Closure Compiler by Este.js
// Generated by CoffeeScript 1.4.0
/**
  @fileoverview este.demos.app.todomvc.todo.Model.
*/



goog.provide('este.demos.app.todomvc.todo.Model');

goog.require('este.Model');



  

  /**
    @param {Object=} json
    @constructor
    @extends {este.Model}
  */


  este.demos.app.todomvc.todo.Model = function(json) {
    este.demos.app.todomvc.todo.Model.superClass_.constructor.call(this, json);
  }

  goog.inherits(este.demos.app.todomvc.todo.Model, este.Model);

  /**
    @inheritDoc
  */


  este.demos.app.todomvc.todo.Model.prototype.defaults = {
    'title': '',
    'completed': false,
    'editing': false
  };

  /**
    @inheritDoc
  */


  este.demos.app.todomvc.todo.Model.prototype.schema = {
    'title': {
      'set': este.model.setters.trim,
      'validators': {
        'required': este.model.validators.required
      }
    }
  };

  este.demos.app.todomvc.todo.Model.prototype.toggleCompleted = function() {
    var completed;
    completed = this.get('completed');
    return this.set('completed', !completed);
  };

  
